# Generated by Django 4.2.10 on 2024-02-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SleepRecogModel",
            fields=[
                ("sleep_recog_id", models.AutoField(primary_key=True, serialize=False)),
                ("blink_score", models.FloatField()),
                ("move_score", models.FloatField()),
                ("silence", models.FloatField()),
                ("baby_cry", models.FloatField()),
                ("baby_laughter", models.FloatField()),
            ],
        ),
    ]
